### ISSUE TITLE
historical maps

### ISSUE THREAD

**Issue by robin-tunger** [nur-die-tat/nur-die-tat-karte#4]
# Karten: "Neuaufnahme" & "TK25"  (gekachelt)
https://www.geoportal.nrw/themenkarten
(über "Meine Auswahl" Layer auswählbar)
- "Neuaufnahme 1891-1912"
- "TK25 1936-1945"

Vorschlag: mit 1912 anfangen und 1936 aufhören; irgendwo halbwegs zeitlich mittig Übergang schneiden.

**gleiches Ergebnis, anderer Anbieter:**
> http://www.bezreg-koeln.nrw.de/brk_internet/tim-online/index.html
> (etwas kompliziert zu bedienen; siehe Button "Dienst hinzuladen"
> stürzt gelegentlich ab bzw Seite ist nicht mehr aufrufbar)
> - "Historische Karten" - "Neuaufnahme 1891-1912"
> - "Historische Karten" - "TK25 1936-1945"

# Stadtpläne ("gewested")
- 1905 (nur als jpg)
http://www.zeno.org/Meyers-1905/B/K%C3%B6ln
- 1921 (gekachelt)
http://www.landkartenarchiv.de/historischestadtplaene.php?q=landkartenarchiv_coeln_1921
- 1923 (gekachelt)
http://www.landkartenarchiv.de/historischestadtplaene.php?q=landkartenarchiv_coeln_1910

# Anfragen

### Fachleute / -institute
- [x] - histmap BN,              Aw.: Hr Kleefeld fragen!
- [x] - Hr Kleefeld LVR         Aw.: _noch nichts_
- [x] - RheinLandesGes BN, Aw.: _noch nichts_
- [x] - histArch K,                Aw.: check! see folder

### Anbieter
- [ ] - **erstmal besprechen, welche sinnvoll sind! (s.o.), dann:**
- [ ] - geoportal.nrw
- [ ] - TIM online
- [ ] - landkartenarchiv

**Comment by s-zyx** [comment]
Habe eine der Karten mithilfe von QGIS georefernziert. Das Ergebnis kann sich sehen lassen finde ich :)
